version: '3.3'

services:
  record_keeper:
    build: "."
    image: "record_keeper:discord"
    restart: unless-stopped
    volumes: 
      - "./Database/:/usr/src/RecordKeeperBot/database/"
      - "./discord_bot:/usr/src/RecordKeeperBot/discord_bot/" 
    entrypoint: ./RecordKeeperBot.sh
